### ISSUE TITLE
Create a VBS script so that on boot the script runs silently and hidden

### ISSUE THREAD

**Issue by Myth0ne** [Correlander/BetterDiscordAutoInstaller#1]
With the power of ChatGPT I was able to create a vbs script in the root directory of BetterDiscordAutoInstaller and instead replace a shortcut to the startup folder overwriting the BDupdater PS file.

If you create a vbs script that contains the below code

`Set objShell = CreateObject("Wscript.Shell")
objShell.Run "powershell.exe -ExecutionPolicy Bypass -File C:\Users\User\BetterDiscordAutoInstaller\Updater.ps1", 0, False
`

Save it into the root directory above obviously replacing the filepath with your specific one. Then creating a shortcut to the VBS file to the `Shell:Startup` location the script will run completely hidden in the background. Hope this helps :)

**Comment by Correlander** [comment]
VBScript is deprecated so I'm hesitant to use it, it also seems there is a way to do this with only slightly modifying the current approach.

If I add the `-WindowStyle Hidden` flag, it will immediately hide the window. In my testing, I can see it flash for some fraction of a second. This is possibly irrelevant, as I'm testing by running the shortcut, not restarting my PC.

I tried looking for a solution to the flash online. One recommendation was launching PowerShell through cmd with the window minimized by putting `cmd /c start "" ` before the current shortcut path, but that flashes a cmd window instead of a PowerShell window.

This has also made me consider adding an option to the startup manager when creating a new shortcut that allows you to choose whether it is fully hidden, or minimized. It might feel better for some users to have the ability to view it in their taskbar if they wish, but not have it shoved in their face on startup, though there is also something to be said for too many customization options. I mainly consider it because, at least personally, I would be stressed out if I saw a nameless Powershell window flash on startup.

Are there any differences/advantages to the VBScript approach compared to this one? Specifically, I'm curious if the window still flashes using VBScript.

**Comment by Myth0ne** [comment]
There is no window or flash with VBScript

**Comment by Correlander** [comment]
I tested on startup, not just running the shortcut, and there is no flash using the `-WindowStyle Hidden` flag. I will incorporate that into the main branch in a moment. Thanks for the suggestion/idea, as well as for taking the time to open an issue about it : )
